### test jwt: login

POST https://vbenbackend.test.com/api/auth/jwt-login
Content-Type: application/json
Accept: application/json

{
    "email": "turner.louie@example.org",
    "password": "password"
}

### test jwt: get user info
POST https://vbenbackend.test.com/api/auth/jwt-me
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3ZiZW5iYWNrZW5kLnRlc3QuY29tL2FwaS9hdXRoL2p3dC1yZWZyZXNoIiwiaWF0IjoxNzQzNDc3MDQ5LCJleHAiOjE3NDM0ODA2OTIsIm5iZiI6MTc0MzQ3NzA5MiwianRpIjoiMzZ2QVZ6WmxwZ0psQzNKTyIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.sxBzlTYCHlzFMhS4MRlnzIltIQbLsSquyIU-2FZm5Jw
Content-Type: application/json
Accept: application/json

### test jwt: refresh a token
POST https://vbenbackend.test.com/api/auth/jwt-refresh
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3ZiZW5iYWNrZW5kLnRlc3QuY29tL2FwaS9hdXRoL2p3dC1yZWZyZXNoIiwiaWF0IjoxNzQzNDc3MDQ5LCJleHAiOjE3NDM0ODA2OTIsIm5iZiI6MTc0MzQ3NzA5MiwianRpIjoiMzZ2QVZ6WmxwZ0psQzNKTyIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.sxBzlTYCHlzFMhS4MRlnzIltIQbLsSquyIU-2FZm5Jw
Content-Type: application/json
Accept: application/json

### test jwt: logout
POST https://vbenbackend.test.com/api/auth/jwt-logout
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3ZiZW5iYWNrZW5kLnRlc3QuY29tL2FwaS9hdXRoL2p3dC1yZWZyZXNoIiwiaWF0IjoxNzQzNDc3MDQ5LCJleHAiOjE3NDM0ODA2OTIsIm5iZiI6MTc0MzQ3NzA5MiwianRpIjoiMzZ2QVZ6WmxwZ0psQzNKTyIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.sxBzlTYCHlzFMhS4MRlnzIltIQbLsSquyIU-2FZm5Jw
Content-Type: application/json
Accept: application/json
