@baseurl = https://vbenbackend.test.com/api
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3ZiZW5iYWNrZW5kLnRlc3QuY29tL2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNzQ0MDE2MjM2LCJleHAiOjE3NDQwMTk4MzYsIm5iZiI6MTc0NDAxNjIzNiwianRpIjoiS3BJaTJveGt6ZExUb1dYbCIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.C-N02AfmTJ108BZLlEfF8R7mhJNaIHe7b_KbaFSh8io

@jsonHeaders = Content-Type: application/json
Accept: application/json

@token = {{login.response.body.data.accessToken}}

### test login
# @name login
POST {{baseurl}}/auth/login
{{jsonHeaders}}
Accept-Language: zh-TW

# {
#     "username": "super",
#     "password": "password"
# }

{
    "username": "admin",
    "password": "password"
}

# {
#     "username": "lam2",
#     "password": "123456"
# }


### test register
POST {{baseurl}}/auth/register
{{jsonHeaders}}

{
    "name": "super",
    "email": "lam3@gmail.com",
    "password": "123456",
    "password_confirmation": "123456"
}

### test get user info
GET {{baseurl}}/auth/me
{{jsonHeaders}}
Authorization: Bearer {{token}}

###
GET {{baseurl}}/user/info
{{jsonHeaders}}
Authorization: Bearer {{token}}

### test logout
POST {{baseurl}}/auth/logout
{{jsonHeaders}}
Authorization: Bearer {{token}}


### test refresh a token
POST {{baseurl}}/auth/refresh
{{jsonHeaders}}
Authorization: Bearer {{token}}


###
GET {{baseurl}}/system/menu/list
{{jsonHeaders}}
Authorization: Bearer {{token}}

###
GET {{baseurl}}/system/user-menu
{{jsonHeaders}}
Authorization: Bearer {{token}}

### create menu
POST {{baseurl}}/system/menu
{{jsonHeaders}}
Authorization: Bearer {{token}}

{
    "name": "test1",
    "path": "/test1",
    "type": "menu",
    "status": 1,
    "pid": 1,
    "meta": {
        "title": "测试菜单",
        "icon": "carbon:add-filled",
        "activeIcon": "carbon:apps",
        "affixTab": true
    },
    "component": "/_core/about/index",
    "authCode": "test1"
}

# {
#     "name": "新菜单2",
#     "slug": "new menu2",
#     "type": "catalog",
#     "url": "/new-menu-url",
#     "component": null,
#     "route_name": "new_menu_route",
#     "icon": "aaa",
#     "parent_id": 1,
#     "permission": "bbb",
#     "order": 100,
#     "active": 0
# }

### update menu
PUT {{baseurl}}/system/menu/30
{{jsonHeaders}}
Authorization: Bearer {{token}}

{
    "name": "test1",
    "path": "/test1",
    "type": "menu",
    "status": 1,
    "pid": 1,
    "meta": {
        "title": "测试菜单2",
        "icon": "carbon:add-filled",
        "activeIcon": "carbon:apps",
        "affixTab": true
    },
    "component": "/_core/about/index",
    "authCode": "test111"
}


# {
#     "name": "test",
#     "path": "/test",
#     "type": "menu",
#     "status": 1,
#     "pid": 1,
#     "meta": {
#         "title": "测试菜单",
#         "icon": "carbon:add-filled",
#         "activeIcon": "carbon:apps",
#         "affixTab": true
#     },
#     "component": "/_core/about/index",
# }

# {
#     "name": "新菜单11",
#     "slug": "new menu1",
#     "permission": "ccc"
# }

### del menu
DELETE {{baseurl}}/system/menu/30
{{jsonHeaders}}
Authorization: Bearer {{token}}

###
GET {{baseurl}}/system/menu/3
{{jsonHeaders}}
Authorization: Bearer {{token}}

###
GET {{baseurl}}/system/menu/name-exists?name=test
{{jsonHeaders}}
Authorization: Bearer {{token}}

###
GET {{baseurl}}/system/menu/path-exists?path=%2Ftestmenu
{{jsonHeaders}}
Authorization: Bearer {{token}}


### get user own menus
GET {{baseurl}}/user-menu
{{jsonHeaders}}
Authorization: Bearer {{token}}


### get user list
GET {{baseurl}}/users
{{jsonHeaders}}
Authorization: Bearer {{token}}


### get single user
GET {{baseurl}}/users/1
{{jsonHeaders}}
Authorization: Bearer {{token}}


### create user
POST {{baseurl}}/users
{{jsonHeaders}}
Authorization: Bearer {{token}}

{
    "name": "New User",
    "email": "new@example.com",
    "password": "password",
    "roles": ["user"]
}


### update user
PUT {{baseurl}}/users/6
{{jsonHeaders}}
Authorization: Bearer {{token}}

{
    "name": "New User2",
    "email": "new@example.com",
    "password": "password",
    "roles": ["user"]
}

### delete user
DELETE {{baseurl}}/users/6
{{jsonHeaders}}
Authorization: Bearer {{token}}

###
GET {{baseurl}}/system/role/list
{{jsonHeaders}}
Authorization: Bearer {{token}}

### get specify role
GET {{baseurl}}/roles/5
{{jsonHeaders}}
Authorization: Bearer {{token}}

### create role
POST {{baseurl}}/roles
{{jsonHeaders}}
Authorization: Bearer {{token}}

{
    "name": "new-role",
    "permissions": ["view articles", "create articles"]
}

### update role
PUT {{baseurl}}/roles/6
{{jsonHeaders}}
Authorization: Bearer {{token}}

{
    "name": "new-role2",
    "permissions": ["view articles", "create articles"]
}

### delete role
DELETE {{baseurl}}/roles/7
{{jsonHeaders}}
Authorization: Bearer {{token}}


### get all permissions
GET {{baseurl}}/permissions
{{jsonHeaders}}
Authorization: Bearer {{token}}


### get specify permission
GET {{baseurl}}/permissions/1
{{jsonHeaders}}
Authorization: Bearer {{token}}

### create permission
POST {{baseurl}}/permissions
{{jsonHeaders}}
Authorization: Bearer {{token}}

{
    "name": "new_permission"
}

### update permission
PUT {{baseurl}}/permissions/12
{{jsonHeaders}}
Authorization: Bearer {{token}}

{
    "name": "new_permission2"
}

### delete permission
DELETE {{baseurl}}/permissions/12
{{jsonHeaders}}
Authorization: Bearer {{token}}


###
GET {{baseurl}}/system/dept/list
{{jsonHeaders}}
Authorization: Bearer {{token}}

###
POST {{baseurl}}/system/dept
{{jsonHeaders}}
Authorization: Bearer {{token}}

{
    "parent_id": 3,
    "name": "Client 4",
    "order": 12,
    "remark": "aaaa"
}

###
GET {{baseurl}}/system/dept/10
{{jsonHeaders}}
Authorization: Bearer {{token}}

###
PUT {{baseurl}}/system/dept/10
{{jsonHeaders}}
Authorization: Bearer {{token}}

{
    "name": "bvbvb"
}


###
DELETE {{baseurl}}/system/dept/10
{{jsonHeaders}}
Authorization: Bearer {{token}}
