@baseurl = https://vbenbackend.test.com/api
@jsonHeaders = Content-Type: application/json
Accept: application/json

@token = {{login.response.body.data.accessToken}}

### test login
# @name login
POST {{baseurl}}/auth/login
{{jsonHeaders}}
Accept-Language: zh-TW

{
    "username": "super",
    "password": "password"
}

# {
#     "username": "admin",
#     "password": "password"
# }

# {
#     "username": "user",
#     "password": "password"
# }

# {
#     "username": "lam1",
#     "password": "12345678"
# }


### get website data
GET {{baseurl}}/leguo/website
{{jsonHeaders}}
Accept-Language: zh-TW
Authorization: Bearer {{token}}

### update website data
PUT {{baseurl}}/leguo/website
{{jsonHeaders}}
Accept-Language: en-US
Authorization: Bearer {{token}}

{
    "desc": "測試内容"
}

### get goods category list
GET {{baseurl}}/leguo/goods-category?p=1&ps=2
{{jsonHeaders}}
Authorization: Bearer {{token}}

###
GET {{baseurl}}/leguo/goods-category/1
{{jsonHeaders}}
Authorization: Bearer {{token}}

### create goods category
POST {{baseurl}}/leguo/goods-category
{{jsonHeaders}}
Authorization: Bearer {{token}}
Accept-Language: zh-TW

{
    "name": "水果5",
    "desc": "aaaaaaa",
    "status": 1
}

### update goods category
PUT {{baseurl}}/leguo/goods-category/11
{{jsonHeaders}}
Authorization: Bearer {{token}}
Accept-Language: zh-TW

{
    "name": "水果2",
    "desc": "bbbb",
    "status": 1
}

### delete goods category
DELETE {{baseurl}}/leguo/goods-category/1
{{jsonHeaders}}
Authorization: Bearer {{token}}
Accept-Language: zh-TW

